# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from tremendous_python_sdk.type.invoices_get_all_response_invoices import InvoicesGetAllResponseInvoices

class RequiredInvoicesGetAllResponse(TypedDict):
    invoices: InvoicesGetAllResponseInvoices

    # The total number of invoices across all pages
    total_count: int

class OptionalInvoicesGetAllResponse(TypedDict, total=False):
    pass

class InvoicesGetAllResponse(RequiredInvoicesGetAllResponse, OptionalInvoicesGetAllResponse):
    pass
