# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from tremendous_python_sdk.type.invoices_get_by_id_response_invoice_orders import InvoicesGetByIdResponseInvoiceOrders
from tremendous_python_sdk.type.invoices_get_by_id_response_invoice_rewards import InvoicesGetByIdResponseInvoiceRewards

class RequiredInvoicesGetByIdResponseInvoice(TypedDict):
    # The invoice number
    id: str

    # Amount of the invoice in USD
    amount: typing.Union[int, float]

    # Status of this invoice  <table>   <thead>     <tr>       <th>Status</th>       <th>Description</th>     </tr>   </thead>   <tbody>     <tr>       <td><code>DELETED</code></td>       <td>Invoice has been deleted by your organization</td>     </tr>     <tr>       <td><code>PAID</code></td>       <td>Invoice has been paid by your organization</td>     </tr>     <tr>       <td><code>OPEN</code></td>       <td>Invoice has been created by your organization but has not been paid, yet</td>     </tr>   </tbody> </table> 
    status: str

    # Timestamp of when the invoice has been created. 
    created_at: date

    # Timestamp of when the invoice has been paid. 
    paid_at: typing.Optional[date]

class OptionalInvoicesGetByIdResponseInvoice(TypedDict, total=False):
    # Reference to the purchase order number within your organization
    po_number: typing.Optional[str]

    orders: InvoicesGetByIdResponseInvoiceOrders

    rewards: InvoicesGetByIdResponseInvoiceRewards

class InvoicesGetByIdResponseInvoice(RequiredInvoicesGetByIdResponseInvoice, OptionalInvoicesGetByIdResponseInvoice):
    pass
