# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from tremendous_python_sdk.type.members_create_new_member500_response_errors import MembersCreateNewMember500ResponseErrors

class RequiredMembersCreateNewMember500Response(TypedDict):
    errors: MembersCreateNewMember500ResponseErrors

class OptionalMembersCreateNewMember500Response(TypedDict, total=False):
    pass

class MembersCreateNewMember500Response(RequiredMembersCreateNewMember500Response, OptionalMembersCreateNewMember500Response):
    pass
