# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from tremendous_python_sdk.type.orders_approve_order_by_id422_response_errors import OrdersApproveOrderById422ResponseErrors

class RequiredOrdersApproveOrderById422Response(TypedDict):
    errors: OrdersApproveOrderById422ResponseErrors

class OptionalOrdersApproveOrderById422Response(TypedDict, total=False):
    pass

class OrdersApproveOrderById422Response(RequiredOrdersApproveOrderById422Response, OptionalOrdersApproveOrderById422Response):
    pass
