# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredProductsGetByIdResponseProductSkusItem(TypedDict):
    # Minimal denomination that this product supports (in the product's currency)
    min: typing.Union[int, float]

    # Maximum denomination that this product supports (in the product's currency)
    max: typing.Union[int, float]

class OptionalProductsGetByIdResponseProductSkusItem(TypedDict, total=False):
    pass

class ProductsGetByIdResponseProductSkusItem(RequiredProductsGetByIdResponseProductSkusItem, OptionalProductsGetByIdResponseProductSkusItem):
    pass
