# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from tremendous_python_sdk.type.rewards_get_single_reward404_response_errors import RewardsGetSingleReward404ResponseErrors

class RequiredRewardsGetSingleReward404Response(TypedDict):
    errors: RewardsGetSingleReward404ResponseErrors

class OptionalRewardsGetSingleReward404Response(TypedDict, total=False):
    pass

class RewardsGetSingleReward404Response(RequiredRewardsGetSingleReward404Response, OptionalRewardsGetSingleReward404Response):
    pass
