# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from tremendous_python_sdk.type.reward_without_link_custom_fields import RewardWithoutLinkCustomFields
from tremendous_python_sdk.type.reward_without_link_delivery import RewardWithoutLinkDelivery
from tremendous_python_sdk.type.reward_without_link_products import RewardWithoutLinkProducts
from tremendous_python_sdk.type.reward_without_link_recipient import RewardWithoutLinkRecipient
from tremendous_python_sdk.type.reward_without_link_value import RewardWithoutLinkValue

class RequiredRewardWithoutLink(TypedDict):
    pass

class OptionalRewardWithoutLink(TypedDict, total=False):
    # Tremendous ID of the reward
    id: str

    # Tremendous ID of the order this reward is part of.
    order_id: str

    # Date the reward was created
    created_at: datetime

    # ID of the campaign in your account, that defines the available products (different gift cards, charity, etc.) that the recipient can choose from. 
    campaign_id: typing.Optional[str]

    products: RewardWithoutLinkProducts

    value: RewardWithoutLinkValue

    recipient: RewardWithoutLinkRecipient

    # Timestamp of reward delivery within the next year. Note that if date-time is provided, the time values will be ignored.
    deliver_at: date

    custom_fields: RewardWithoutLinkCustomFields

    delivery: RewardWithoutLinkDelivery

class RewardWithoutLink(RequiredRewardWithoutLink, OptionalRewardWithoutLink):
    pass
