# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from tremendous_python_sdk.type.rewards_get_single_reward_response_reward_custom_fields import RewardsGetSingleRewardResponseRewardCustomFields
from tremendous_python_sdk.type.rewards_get_single_reward_response_reward_delivery import RewardsGetSingleRewardResponseRewardDelivery
from tremendous_python_sdk.type.rewards_get_single_reward_response_reward_recipient import RewardsGetSingleRewardResponseRewardRecipient
from tremendous_python_sdk.type.rewards_get_single_reward_response_reward_value import RewardsGetSingleRewardResponseRewardValue

class RequiredRewardsGetSingleRewardResponseReward(TypedDict):
    pass

class OptionalRewardsGetSingleRewardResponseReward(TypedDict, total=False):
    # Tremendous ID of the reward
    id: str

    # Tremendous ID of the order this reward is part of.
    order_id: str

    # Date the reward was created
    created_at: datetime

    value: RewardsGetSingleRewardResponseRewardValue

    recipient: RewardsGetSingleRewardResponseRewardRecipient

    # Timestamp of reward delivery within the next year. Note that if date-time is provided, the time values will be ignored.
    deliver_at: date

    custom_fields: RewardsGetSingleRewardResponseRewardCustomFields

    delivery: RewardsGetSingleRewardResponseRewardDelivery

class RewardsGetSingleRewardResponseReward(RequiredRewardsGetSingleRewardResponseReward, OptionalRewardsGetSingleRewardResponseReward):
    pass
