# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from tremendous_python_sdk.type.reward_custom_fields import RewardCustomFields
from tremendous_python_sdk.type.reward_delivery import RewardDelivery
from tremendous_python_sdk.type.reward_products import RewardProducts
from tremendous_python_sdk.type.reward_recipient import RewardRecipient
from tremendous_python_sdk.type.reward_value import RewardValue

class RequiredReward(TypedDict):
    pass

class OptionalReward(TypedDict, total=False):
    # Tremendous ID of the reward
    id: str

    # Tremendous ID of the order this reward is part of.
    order_id: str

    # Date the reward was created
    created_at: datetime

    # ID of the campaign in your account, that defines the available products (different gift cards, charity, etc.) that the recipient can choose from. 
    campaign_id: typing.Optional[str]

    products: RewardProducts

    value: RewardValue

    recipient: RewardRecipient

    # Timestamp of reward delivery within the next year. Note that if date-time is provided, the time values will be ignored.
    deliver_at: date

    custom_fields: RewardCustomFields

    delivery: RewardDelivery

class Reward(RequiredReward, OptionalReward):
    pass
