# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from tremendous_python_sdk.pydantic.order_with_link_rewards_item_custom_fields import OrderWithLinkRewardsItemCustomFields
from tremendous_python_sdk.pydantic.order_with_link_rewards_item_delivery import OrderWithLinkRewardsItemDelivery
from tremendous_python_sdk.pydantic.order_with_link_rewards_item_products import OrderWithLinkRewardsItemProducts
from tremendous_python_sdk.pydantic.order_with_link_rewards_item_recipient import OrderWithLinkRewardsItemRecipient
from tremendous_python_sdk.pydantic.order_with_link_rewards_item_value import OrderWithLinkRewardsItemValue

class OrderWithLinkRewardsItem(BaseModel):
    # Tremendous ID of the reward
    id: typing.Optional[str] = Field(None, alias='id')

    # Tremendous ID of the order this reward is part of.
    order_id: typing.Optional[str] = Field(None, alias='order_id')

    # Date the reward was created
    created_at: typing.Optional[datetime] = Field(None, alias='created_at')

    # ID of the campaign in your account, that defines the available products (different gift cards, charity, etc.) that the recipient can choose from. 
    campaign_id: typing.Optional[typing.Optional[str]] = Field(None, alias='campaign_id')

    products: typing.Optional[OrderWithLinkRewardsItemProducts] = Field(None, alias='products')

    value: typing.Optional[OrderWithLinkRewardsItemValue] = Field(None, alias='value')

    recipient: typing.Optional[OrderWithLinkRewardsItemRecipient] = Field(None, alias='recipient')

    # Timestamp of reward delivery within the next year. Note that if date-time is provided, the time values will be ignored.
    deliver_at: typing.Optional[date] = Field(None, alias='deliver_at')

    custom_fields: typing.Optional[OrderWithLinkRewardsItemCustomFields] = Field(None, alias='custom_fields')

    delivery: typing.Optional[OrderWithLinkRewardsItemDelivery] = Field(None, alias='delivery')
    class Config:
        arbitrary_types_allowed = True
