# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from tremendous_python_sdk import schemas  # noqa: F401


class DeliveryStatus(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Current status of the delivery of the reward:

* `SCHEDULED` - Reward is scheduled for delivery and will be delivered soon.
* `FAILED` - Delivery of reward failed (e.g. email bounced).
* `SUCCEEDED` - Reward was successfully delivered (email or text message delivered or reward link opened).
* `PENDING` - Delivery is pending but not yet scheduled.

    """


    class MetaOapg:
        enum_value_to_name = {
            "SCHEDULED": "SCHEDULED",
            "FAILED": "FAILED",
            "SUCCEEDED": "SUCCEEDED",
            "PENDING": "PENDING",
        }
    
    @schemas.classproperty
    def SCHEDULED(cls):
        return cls("SCHEDULED")
    
    @schemas.classproperty
    def FAILED(cls):
        return cls("FAILED")
    
    @schemas.classproperty
    def SUCCEEDED(cls):
        return cls("SUCCEEDED")
    
    @schemas.classproperty
    def PENDING(cls):
        return cls("PENDING")
