# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from tremendous_python_sdk import schemas  # noqa: F401


class DeliveryMethod(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    How to deliver the reward to the recipient.

<table>
  <thead>
    <tr>
      <th>Delivery Method</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>EMAIL</code></td>
      <td>Deliver the reward to the recipient by email</td>
    </tr>
    <tr>
      <td><code>LINK</code></td>
      <td>
        <p>Deliver the reward to the recipient via a link.</p>
        <p>The link can be retrieved on a successfully ordered reward via the <code>/rewards</code> or <code>/rewards/{id}</code> endpoint. That link must then be  delivered to the recipient out-of-band.</p>
      </td>
    </tr>
    <tr>
      <td><code>PHONE</code></td>
      <td>Deliver the reward to the recipient by SMS</td>
    </tr>
  </tbody>
</table>

    """
    
    @schemas.classproperty
    def EMAIL(cls):
        return cls("EMAIL")
    
    @schemas.classproperty
    def LINK(cls):
        return cls("LINK")
    
    @schemas.classproperty
    def PHONE(cls):
        return cls("PHONE")
