# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

import unittest

import tremendous_python_sdk
from tremendous_python_sdk.model.funding_sources_get_all_response_funding_sources import FundingSourcesGetAllResponseFundingSources
from tremendous_python_sdk import configuration


class TestFundingSourcesGetAllResponseFundingSources(unittest.TestCase):
    """FundingSourcesGetAllResponseFundingSources unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
