# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

import unittest

import tremendous_python_sdk
from tremendous_python_sdk.model.rewards_list_all_rewards500_response_errors import RewardsListAllRewards500ResponseErrors
from tremendous_python_sdk import configuration


class TestRewardsListAllRewards500ResponseErrors(unittest.TestCase):
    """RewardsListAllRewards500ResponseErrors unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
