# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

import unittest

import tremendous_python_sdk
from tremendous_python_sdk.model.invoices_create_and_fund_account_balance400_response_errors import InvoicesCreateAndFundAccountBalance400ResponseErrors
from tremendous_python_sdk import configuration


class TestInvoicesCreateAndFundAccountBalance400ResponseErrors(unittest.TestCase):
    """InvoicesCreateAndFundAccountBalance400ResponseErrors unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
