# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

import unittest

import tremendous_python_sdk
from tremendous_python_sdk.model.invoices_create_and_fund_account_balance_response import InvoicesCreateAndFundAccountBalanceResponse
from tremendous_python_sdk import configuration


class TestInvoicesCreateAndFundAccountBalanceResponse(unittest.TestCase):
    """InvoicesCreateAndFundAccountBalanceResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
