# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

import unittest

import tremendous_python_sdk
from tremendous_python_sdk.model.orders_approve_order_by_id_response_order_reward_custom_fields_item import OrdersApproveOrderByIdResponseOrderRewardCustomFieldsItem
from tremendous_python_sdk import configuration


class TestOrdersApproveOrderByIdResponseOrderRewardCustomFieldsItem(unittest.TestCase):
    """OrdersApproveOrderByIdResponseOrderRewardCustomFieldsItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
