# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

import unittest

import tremendous_python_sdk
from tremendous_python_sdk.model.orders_get_order_by_id429_response_errors import OrdersGetOrderById429ResponseErrors
from tremendous_python_sdk import configuration


class TestOrdersGetOrderById429ResponseErrors(unittest.TestCase):
    """OrdersGetOrderById429ResponseErrors unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
