# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

from tremendous_python_sdk.paths.invoices.post import CreateAndFundAccountBalance
from tremendous_python_sdk.paths.invoices.get import GetAll
from tremendous_python_sdk.paths.invoices_id.get import GetById
from tremendous_python_sdk.paths.invoices_id_csv.get import GetCsv
from tremendous_python_sdk.paths.invoices_id_pdf.get import GetPdf
from tremendous_python_sdk.paths.invoices_id.delete import RemoveInvoice
from tremendous_python_sdk.apis.tags.invoices_api_raw import InvoicesApiRaw


class InvoicesApi(
    CreateAndFundAccountBalance,
    GetAll,
    GetById,
    GetCsv,
    GetPdf,
    RemoveInvoice,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: InvoicesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = InvoicesApiRaw(api_client)
