# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

from tremendous_python_sdk.paths.invoices.post import CreateAndFundAccountBalanceRaw
from tremendous_python_sdk.paths.invoices.get import GetAllRaw
from tremendous_python_sdk.paths.invoices_id.get import GetByIdRaw
from tremendous_python_sdk.paths.invoices_id_csv.get import GetCsvRaw
from tremendous_python_sdk.paths.invoices_id_pdf.get import GetPdfRaw
from tremendous_python_sdk.paths.invoices_id.delete import RemoveInvoiceRaw


class InvoicesApiRaw(
    CreateAndFundAccountBalanceRaw,
    GetAllRaw,
    GetByIdRaw,
    GetCsvRaw,
    GetPdfRaw,
    RemoveInvoiceRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
