# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

from tremendous_python_sdk.paths.order_approvals_id_approve.post import ApproveOrderByIdRaw
from tremendous_python_sdk.paths.orders.post import CreateOrderRaw
from tremendous_python_sdk.paths.orders.get import GetListRaw
from tremendous_python_sdk.paths.orders_id.get import GetOrderByIdRaw
from tremendous_python_sdk.paths.order_approvals_id_reject.post import RejectByIdRaw


class OrdersApiRaw(
    ApproveOrderByIdRaw,
    CreateOrderRaw,
    GetListRaw,
    GetOrderByIdRaw,
    RejectByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
