# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

from tremendous_python_sdk.paths.order_approvals_id_approve.post import ApproveOrderById
from tremendous_python_sdk.paths.orders.post import CreateOrder
from tremendous_python_sdk.paths.orders.get import GetList
from tremendous_python_sdk.paths.orders_id.get import GetOrderById
from tremendous_python_sdk.paths.order_approvals_id_reject.post import RejectById
from tremendous_python_sdk.apis.tags.orders_api_raw import OrdersApiRaw


class OrdersApi(
    ApproveOrderById,
    CreateOrder,
    GetList,
    GetOrderById,
    RejectById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: OrdersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = OrdersApiRaw(api_client)
