# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

from tremendous_python_sdk.paths.organizations_create_api_key.post import CreateApiKeyRaw
from tremendous_python_sdk.paths.organizations.post import CreateNewOrganizationRaw
from tremendous_python_sdk.paths.organizations.get import GetListRaw
from tremendous_python_sdk.paths.organizations_id.get import GetOrganizationRaw


class OrganizationsApiRaw(
    CreateApiKeyRaw,
    CreateNewOrganizationRaw,
    GetListRaw,
    GetOrganizationRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
