# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

from tremendous_python_sdk.paths.organizations_create_api_key.post import CreateApiKey
from tremendous_python_sdk.paths.organizations.post import CreateNewOrganization
from tremendous_python_sdk.paths.organizations.get import GetList
from tremendous_python_sdk.paths.organizations_id.get import GetOrganization
from tremendous_python_sdk.apis.tags.organizations_api_raw import OrganizationsApiRaw


class OrganizationsApi(
    CreateApiKey,
    CreateNewOrganization,
    GetList,
    GetOrganization,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: OrganizationsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = OrganizationsApiRaw(api_client)
