# coding: utf-8

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

from tremendous_python_sdk.paths.webhooks.post import CreateWebhookRaw
from tremendous_python_sdk.paths.webhooks.get import GetDetailsRaw
from tremendous_python_sdk.paths.webhooks_id.get import GetDetails0Raw
from tremendous_python_sdk.paths.webhooks_id_events.get import ListEventsRaw
from tremendous_python_sdk.paths.webhooks_id_simulate.post import TriggerEventRaw


class WebhooksApiRaw(
    CreateWebhookRaw,
    GetDetailsRaw,
    GetDetails0Raw,
    ListEventsRaw,
    TriggerEventRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
