# coding: utf-8

# flake8: noqa

"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

__version__ = "2"

# import ApiClient
from tremendous_python_sdk.api_client import ApiClient

# import Configuration
from tremendous_python_sdk.configuration import Configuration

# import exceptions
from tremendous_python_sdk.exceptions import OpenApiException
from tremendous_python_sdk.exceptions import ApiAttributeError
from tremendous_python_sdk.exceptions import ApiTypeError
from tremendous_python_sdk.exceptions import ApiValueError
from tremendous_python_sdk.exceptions import ApiKeyError
from tremendous_python_sdk.exceptions import ApiException

from tremendous_python_sdk.client import Tremendous
