# coding: utf-8
"""
    API Endpoints

    Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

    The version of the OpenAPI document: 2
    Contact: developers@tremendous.com
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from tremendous_python_sdk.client_custom import ClientCustom
from tremendous_python_sdk.configuration import Configuration
from tremendous_python_sdk.api_client import ApiClient
from tremendous_python_sdk.type_util import copy_signature
from tremendous_python_sdk.apis.tags.balance_transactions_api import BalanceTransactionsApi
from tremendous_python_sdk.apis.tags.campaigns_api import CampaignsApi
from tremendous_python_sdk.apis.tags.fields_api import FieldsApi
from tremendous_python_sdk.apis.tags.funding_sources_api import FundingSourcesApi
from tremendous_python_sdk.apis.tags.invoices_api import InvoicesApi
from tremendous_python_sdk.apis.tags.members_api import MembersApi
from tremendous_python_sdk.apis.tags.orders_api import OrdersApi
from tremendous_python_sdk.apis.tags.organizations_api import OrganizationsApi
from tremendous_python_sdk.apis.tags.products_api import ProductsApi
from tremendous_python_sdk.apis.tags.rewards_api import RewardsApi
from tremendous_python_sdk.apis.tags.webhooks_api import WebhooksApi



class Tremendous(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.balance_transactions: BalanceTransactionsApi = BalanceTransactionsApi(api_client)
        self.campaigns: CampaignsApi = CampaignsApi(api_client)
        self.fields: FieldsApi = FieldsApi(api_client)
        self.funding_sources: FundingSourcesApi = FundingSourcesApi(api_client)
        self.invoices: InvoicesApi = InvoicesApi(api_client)
        self.members: MembersApi = MembersApi(api_client)
        self.orders: OrdersApi = OrdersApi(api_client)
        self.organizations: OrganizationsApi = OrganizationsApi(api_client)
        self.products: ProductsApi = ProductsApi(api_client)
        self.rewards: RewardsApi = RewardsApi(api_client)
        self.webhooks: WebhooksApi = WebhooksApi(api_client)
